CREATE TABLE CLIENTES (
		CODIGO_CLIENTE BIGINT NOT NULL AUTO_INCREMENT,
        TIPO VARCHAR(2) NOT NULL,
        CPF_OU_CNPJ VARCHAR(14) NOT NULL,
        NOME VARCHAR(500) NOT NULL,

        PRIMARY KEY(CODIGO_CLIENTE)
)